### ISSUE TITLE
Installation problem: html5lib

### ISSUE THREAD

**Issue by btseytlin** [Dmitri-Sintsov/djk-sample#1]
During installation (Windows 32, Python 3.5) I faced a problem.
Attempting `python manage.py makemigrations` caused this error:
```
ImportError: No module named 'html5lib.filters.base'
```
Attempted to import `html5lib.filters.base` from Python shell and it failed.
Browsing the [html5lib pypi page](https://pypi.python.org/pypi/html5lib) I found this in changelog to version _1.0b9_:
> Move filters._base, treebuilder._base, and treewalkers._base to .base to clarify their status as public.

Importing `html5lib.filters._base` from Python shell worked.
Evidently `pip install html5lib`, caused by `pip install -r requirements.txt`, installed a version lower than _1.0b9_, but the project relies on a higher version.

To fix the issue just install a later version of `html5lib`:
`pip install html5lib==1.0b10`

**Comment by Dmitri-Sintsov** [comment]
I supposedly incorrectly fixated the version of `html5lib` in

https://github.com/Dmitri-Sintsov/django-jinja-knockout/blob/a9a2193e21a5b26b2f387e7d4f4387ceae930c4b/requirements.txt

Because it's not even being directly used by `django-jinja-knockout` module but by `bleach` module.

However when I removed `html5lib<0.99999999` from there and performed `pip3 install -U -r requirements.txt` it still installs the following versions of packages in Ubuntu 14.04 Python 3.4:

```
user@ispdev:~/work/djk_sample/djk-sample$ pip3 freeze|grep -E 'bleach|html5lib'
bleach==2.0.0
html5lib==0.999999999

```
It must be because `html5lib 1.0b10` is still beta and is not installed by pypi by default.

However with such `requirements.txt` without `html5lib` version fixation it breaks the test with the following error:

```
  File "/home/user/work/djk_sample/lib/python3.4/site-packages/html5lib/__init__.py", line 16, in <module>
    from .html5parser import HTMLParser, parse, parseFragment
  File "/home/user/work/djk_sample/lib/python3.4/site-packages/html5lib/html5parser.py", line 11, in <module>
    from . import _inputstream
  File "/home/user/work/djk_sample/lib/python3.4/site-packages/html5lib/_inputstream.py", line 9, in <module>
    import webencodings
ImportError: No module named 'webencodings'

```
and even updating to beta of html5lib does not fix that
`pip install html5lib==1.0b10`

```
user@ispdev:~/work/djk_sample/djk-sample$ pip3 install webencodings
Downloading/unpacking webencodings
  Downloading webencodings-0.5.tar.gz
Cleaning up...
setuptools must be installed to install from a source distribution
Storing debug log for failure in /home/user/.pip/pip.log
user@ispdev:~/work/djk_sample/djk-sample$ pip3 install setuptools
Requirement already satisfied (use --upgrade to upgrade): setuptools in /home/user/work/djk_sample/lib/python3.4/site-packages
Cleaning up...

```
It seems that the `setuptools==34.3.1` which is shipped with Ubuntu 14.04 / Python 3.4 is too outdated to build `webencodings`.

**Comment by Dmitri-Sintsov** [comment]
Things are much better in Ubuntu 16.04 / Python 3.5:
```
sdv@questpc:~/work/djk_sample/djk-sample$ pip3 list|grep -E 'bleach|html5lib|webencodings'
bleach (2.0.0)
html5lib (0.999999999)
webencodings (0.5)
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
It complained about not being able to build binary wheel, yet the packages are installed and the project is running normally.

After doing `pip3 install -U pip wheel setuptools` in Ubuntu 14.04 / Python 3.4 now it is able to install `webencodings` module required to run `bleach` / `html5lib`. I a bit dislike such approach because it may make tests more fragile.

However because the time of Ubuntu 14.04 comes to the end while Ubuntu 16.04 will be supported in a longer time, I will leave `requirements.txt` without the fixation of `html5lib` version. I updated https://github.com/Dmitri-Sintsov/djk-sample/commit/20bc5d00d50df5ab5be889341598651b622ee2f4 instead.

Please let me know whether it works for you.

**Comment by btseytlin** [comment]
Thanks for the insight! Bet this will help someone in future.
